# Generated by Django 5.0.3 on 2024-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0040_processinterval_startend_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_hidden_in_second',
            field=models.BooleanField(default=False),
        ),
    ]
