# Generated by Django 5.0.3 on 2024-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0041_process_is_hidden_in_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_hidden_in_second',
        ),
    ]
