# Generated by Django 5.0.3 on 2024-11-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0043_process_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='hidden',
            new_name='visible',
        ),
    ]
