# Generated by Django 5.0.3 on 2024-11-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('main_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_processes', to='sample.mainprocess')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sub_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to='sample.subprocess')),
            ],
        ),
    ]
