# Generated by Django 5.0.3 on 2024-11-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprocess',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
