# Generated by Django 5.0.3 on 2024-11-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_mainprocess_name_alter_subprocess_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocess',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProductionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sub_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_times', to='sample.subprocess')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeInterval',
        ),
    ]
