# Generated by Django 5.0.3 on 2024-11-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_subprocess_additional_info_productiontime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprocess',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mainprocess',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mainprocess',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductionTime',
        ),
    ]
