# Generated by Django 5.0.3 on 2024-11-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_remove_mainprocess_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprocess',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField()),
                ('time_slot', models.TimeField()),
                ('main_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.mainprocess')),
                ('sub_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.subprocess')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionData',
        ),
    ]
