# Generated by Django 5.0.3 on 2024-11-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_mainprocess_name_alter_subprocess_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocess',
            name='main_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='sample.mainprocess'),
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True)),
                ('time_interval', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sample.subprocess')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionEntry',
        ),
    ]
