# Generated by Django 5.0.3 on 2024-11-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_subprocess_main_process_productiondata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocess',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductionData',
        ),
    ]
